config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :exports, only: [:index] do
    collection do
      get :stream_csv
      get :normal_csv
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.in_batches(&block)
    #find_each will batch the results instead of getting all in one go
    find_each(batch_size: 100) do |transaction|
      yield transaction
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exports_controller.rb
require 'csv'
class ExportsController < ApplicationController

  def index
  end

  def normal_csv
    respond_to do |format|
      format.csv do
        csv = generate_csv(User.column_names, User.all)
        send_data(csv)
      end
    end
  end

  def stream_csv
    respond_to do |format|
      format.csv do
        csv_enumerator = generate_streaming_csv(User.column_names, User.all)
        render_streaming_csv(csv_enumerator)
      end
    end
  end

  private

  def generate_csv(column_names, records)
    CSV.generate do |csv|
      csv << column_names # add headers to the CSV

      records.each do |record|
        csv << record.attributes.values_at(*column_names)
      end
    end
  end

  def generate_streaming_csv(column_names, records)
    Enumerator.new do |csv|
      csv << column_names.to_csv # add headers to the CSV

      records.each do |record|
        csv << record.attributes.values_at(*column_names).to_csv
      end
    end
  end

  def render_streaming_csv(csv_enumerator)
    # Delete this header so that Rack knows to stream the content.
    headers.delete("Content-Length")
    # Do not cache results from this action.
    headers["Cache-Control"] = "no-cache"
    # Let the browser know that this file is a CSV.
    headers['Content-Type'] = 'text/csv'
    # Do not buffer the result when using proxy servers.
    headers['X-Accel-Buffering'] = 'no'
    # Set the filename
    headers['Content-Disposition'] = "attachment; filename=\"report.csv\""
    # Set the response body as the enumerator
    self.response_body = csv_enumerator
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exports/index.html.erb
<style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 50px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 50px;
  margin: 4px 50px;
  cursor: pointer;
  border-radius: 2px;
}

.button1 {background-color: #4CAF50}
.button2 {background-color: red}
</style>
</head>
<body>

<%= link_to "Normal CSV Download", normal_csv_exports_path(format: :csv), class: 'button button1'%>
<%= link_to "Streaming CSV Download", stream_csv_exports_path(format: :csv), class: 'button button2'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvStream</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>